version: '3.8'

services:
  nestjs:
    image: node:22-alpine
    container_name: nestjs-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run start:dev"
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
    networks:
      - nestjs-network

  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example-nest
    ports:
      - "5432:5432"
    networks:
      - nestjs-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  nestjs-network:
    driver: bridge

volumes:
  postgres-data:
